## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [47]:
import numpy as np
np.linspace(-1.3, 2.5, 65)

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2. Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [48]:
n = int(input())
np.array([1, 2, 3] * n)

5


array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

3.	Создайте массив первых 10 нечетных целых чисел.

In [49]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [50]:
a = np.zeros((10, 10))
a[:, [0, 9]] = 1
a[[0, 9], 1:8] = 1
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [51]:
b = np.zeros((8, 8))
b[::2, ::2] = 1
b[1::2, 1::2] = 1
print(b)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [52]:
n = int(input())
m = np.empty((n, n), dtype = "int")
for i in range(n):
    for j in range(n):
        m[i][j] = i + j
print(m)

5
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [65]:
v = np.random.randint(1, 10, n)
m = np.random.randint(10, size=(n, n))
print(v, '\n\n', m, '\n\n')
print(np.dot(v, v), '\n\n')
print(np.dot(m, v), '\n\n')
print(np.dot(m, m))

[9 9 5 2 4] 

 [[1 8 4 0 4]
 [9 5 7 4 4]
 [4 4 2 0 1]
 [3 4 8 6 0]
 [2 3 7 5 3]] 


207 


[117 185  86 115 102] 


[[ 97  76  96  52  52]
 [102 153 145  64  75]
 [ 50  63  55  21  37]
 [ 89 100 104  52  36]
 [ 78  88 104  57  36]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [54]:
c = np.cos(np.linspace(0, 1, int(1 / 0.05) + 1))
s = np.sin(np.linspace(0, 1, int(1 / 0.05) + 1))
list(c) + list(s)

[1.0,
 0.9987502603949663,
 0.9950041652780258,
 0.9887710779360422,
 0.9800665778412416,
 0.9689124217106447,
 0.955336489125606,
 0.9393727128473789,
 0.9210609940028851,
 0.9004471023526769,
 0.8775825618903728,
 0.8525245220595057,
 0.8253356149096782,
 0.7960837985490559,
 0.7648421872844884,
 0.7316888688738209,
 0.6967067093471654,
 0.6599831458849821,
 0.6216099682706644,
 0.5816830894638835,
 0.5403023058681398,
 0.0,
 0.04997916927067833,
 0.09983341664682815,
 0.14943813247359924,
 0.19866933079506122,
 0.24740395925452294,
 0.2955202066613396,
 0.3428978074554514,
 0.3894183423086505,
 0.43496553411123023,
 0.479425538604203,
 0.5226872289306592,
 0.5646424733950355,
 0.6051864057360395,
 0.6442176872376911,
 0.6816387600233341,
 0.7173560908995228,
 0.7512804051402927,
 0.7833269096274834,
 0.8134155047893737,
 0.8414709848078965]

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [61]:
A = np.random.rand(3, 5)*4-1
print(A)

[[ 1.40519098  2.65350546  2.06395635 -0.83675336  2.83831912]
 [-0.36917455 -0.65475998  1.99261213 -0.58563138 -0.71904538]
 [ 1.65560803  1.5865436   2.04694085  1.62089446 -0.87421981]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [66]:
print('сумма всех элементов', A.sum())
print('сумма внутри строк', np.sum(A, 1))
print('сумма внутри столбцов', np.sum(A, 0))
print('среднее значение', np.mean(A, 1))
print('дисперсия', np.var(A, 1))
print('стандартное отклонение', np.std(A, 1))

сумма всех элементов 13.823986523237064
сумма внутри строк [ 8.12421855 -0.33599916  6.03576714]
сумма внутри столбцов [2.69162446 3.58528908 6.10350934 0.19850972 1.24505393]
среднее значение [ 1.62484371 -0.06719983  1.20715343]
дисперсия [1.76623899 1.07458298 1.11071751]
стандартное отклонение [1.32899924 1.03662094 1.05390584]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [69]:
M = np.mean(A, 1)
S = np.std(A, 1)
for i in range(len(A)):
    A[i, :] -= M[i]
    A[i, :] /= S[i]
print(A)

[[-0.16527679  0.77401229  0.3304085  -1.85221856  0.91307457]
 [-0.29130679 -0.56680328  1.98704452 -0.5001168  -0.62881765]
 [ 0.42551677  0.35998489  0.79683345  0.39257875 -1.97491386]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [70]:
A[A[:, 2].argsort()]

array([[-0.16527679,  0.77401229,  0.3304085 , -1.85221856,  0.91307457],
       [ 0.42551677,  0.35998489,  0.79683345,  0.39257875, -1.97491386],
       [-0.29130679, -0.56680328,  1.98704452, -0.5001168 , -0.62881765]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [71]:
B = np.dot(np.transpose(A), A)
C = np.dot(A, np.transpose(A))
print(B, '\n\n', C)

# Обе матрицы симметричны
# Матрица B размера 5х5, С - 3х3
# Сходство: симметричность, тип значений; Отличия: размер, значения, у матрицы С значения на главной диагонали ран

[[ 0.29324059  0.19036698 -0.29438243  0.618865   -0.80809014]
 [ 0.19036698  1.04995011 -0.58367512 -1.00884968  0.3522077 ]
 [-0.29438243 -0.58367512  4.69245927 -1.29292322 -2.5214785 ]
 [ 0.618865   -1.00884968 -1.29292322  3.8349485  -2.1520406 ]
 [-0.80809014  0.3522077  -2.5214785  -2.1520406   5.12940154]] 

 [[ 5.          0.61813815 -2.05880003]
 [ 0.61813815  5.          2.30087247]
 [-2.05880003  2.30087247  5.        ]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [9]:
np.random.seed(1032201708)
np.random.randint(9, size=1)

array([4])